# Backward-compatibility imports
from app.core.db import (
    engine,
    create_db_and_tables,
    get_session,
    UserRoleLink,
    OrderCouponLink,
    RoleInDB,
    UserInDB,
    Address,
    Cart,
    CartItem,
    PaymentMethod,
    Order,
    OrderItem,
    Payment,
    Coupon,
)
from app.features.products.models import (
    CategoryProductLink,
    Category,
    Supplier,
    Brand,
    Description,
    Stock,
    Product,
    ProductReview,
    ProductImage,
)

__all__ = [
    "engine",
    "create_db_and_tables",
    "get_session",
    "UserRoleLink",
    "OrderCouponLink",
    "RoleInDB",
    "UserInDB",
    "Address",
    "Cart",
    "CartItem",
    "PaymentMethod",
    "Order",
    "OrderItem",
    "Payment",
    "Coupon",
    "CategoryProductLink",
    "Category",
    "Supplier",
    "Brand",
    "Description",
    "Stock",
    "Product",
    "ProductReview",
    "ProductImage",
]
